apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    app.kubernetes.io/name: {{ template "app.name" . }}
    {{ if .Values.service.additionalLabels }}
      {{- toYaml .Values.service.additionalLabels | nindent 4 }}
    {{ end }}
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    app: {{ template "app.name" . }}
  # sessionAffinity: None
  type: {{ .Values.service.serviceType }}
